use_frameworks!
target 'TLPhotoPicker_Example' do
  pod 'TLPhotoPicker', :path => '../'

  target 'TLPhotoPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
